### ISSUE TITLE
Capitalized custom color is not seen on front-end

### ISSUE THREAD

**Issue by marceloaof** [tomusborne/generatepress#274]
Hello.
When I create a custom color and name it with capital letters, for example:
"boxColor" or "boxHoverColor",

Until alpha 1, I was not seeing this color applied to blocks neither on the front-end nor on the editor.
Starting on alpha 2, I am still not seeing the color applied to blocks on the front-end, but now I am seeing the color on the editor.

After investigating it,
I discovered that, on front-end, a block colored with the custom color "boxColor"
receives the following attribute on its HTML:
< h6 class="has-button-hover-color-color has-text-color">My Text Here< /h6>

However, at the same time on the front-end, this custom color "boxColor" is named differently on the style.min.css stylesheet:
.has-boxColor-color { color:#f7f7f7; }

Intermediate consideration: custom colors named according to camelCase, capitalized, are not seen applied to blocks on the front-end because the color is named differently on the block HTML and on GeneratePress' stylesheet.

Further exploring to trace very well the problem, I created a custom color with an uncommon name, in order to explore many naming conventions:
"--boxColor-c-c-ccccccCCCCCCcCcCcCc"

I apply this custom color to a text block.

Here is what happens:
1. Inside the Customizer, hovering the color on the Global Colors section,
✔️ 1.0 The tooltip name is correct: --boxColor-c-c-ccccccCCCCCCcCcCcCc
✔️ 1.1 The colored circle related to the tooltip has a correct HTML attribute: aria-label="--boxColor-c-c-ccccccCCCCCCcCcCcCc" style="color: rgb(247, 247, 247);"
✔️ 1.2 The color is also seen correctly because its related CSS is printed on inline stylesheet as: .has---boxColor-c-c-ccccccCCCCCCcCcCcCc-color { color:#f7f7f7; }

2. Inside the editor, hovering the color on the Gutenberg palette,
❌ 2.0 The tooltip name is wrong: --boxcolor-c-c-ccccccccccccccccccc (could you please report this bug to Gutenberg project?)
✔️ 2.1 But the colored circle related to the tooltip has a correct HTML attribute: style="color: var(----boxColor-c-c-ccccccCCCCCCcCcCcCc);"
✔️ 2.2 The color is seen correctly because its related CSS is printed on inline stylesheet as: .has---boxColor-c-c-ccccccCCCCCCcCcCcCc-color { color:#f7f7f7; }

3. Inside the editor, observing a colored text block,
✔️ 3.1 The colored block has a correct HTML attribute: color: var(----boxColor-c-c-ccccccCCCCCCcCcCcCc);
✔️ 3.2 The color is seen correctly because its related CSS is printed on inline stylesheet: .has---boxColor-c-c-ccccccCCCCCCcCcCcCc-color { color:#f7f7f7; }

4. On the front-end, observing a colored text block,
❌ 4.1 The colored block has a wrong HTML attribute: class="has-box-color-c-c-cccccc-ccccc-cc-cc-cc-cc-color has-text-color"
✔️ 4.2 But the color could have been seen correctly because its related CSS is printed on inline stylesheet:
.has---boxColor-c-c-ccccccCCCCCCcCcCcCc-color { color:#f7f7f7; }

Note 1: "background-color" is also impacted by this bug regarding "color".

Note 2: please, observe the color name starts with two dashes. Apparently, the inline stylesheets are working despite different ways in which the stylesheets are printing the beginning of the color name. Sometimes the CSS refers to a color name starting with three dashes; another times there are four dashes, and other times just two dashes. At least this was not a problem in Firefox.

Final consideration: probably you are going to fix this bug by applying custom colors to a block HTML attribute on the front-end using the same method you have considered when applying custom colors to a block HTML attribute inside the editor.

**Comment by JeanPaiva** [comment]
Hey @marceloaof thank you for your report. We will look into it and try to come up with a good solution.

**Comment by tomusborne** [comment]
Should be fixed in the next alpha/beta release: https://github.com/tomusborne/generatepress/pull/276

Thanks!

**Comment by marceloaof** [comment]
Colors named with letters and numbers together (accent1, accent2, ff0000red) are not seen.

**Comment by tomusborne** [comment]
Can you be more specific? Where aren't they seen?

Thanks!

**Comment by marceloaof** [comment]
Yes. I was trying to be succinct after writing so much.
1. Thank you for your fix. I tested it today. I am not able anymore to name colors as "boxColor", "boxHoverColor", unfortunately. At least, people are not going to have problem creating colors because capitalized letters are going to be automatically translated to a hyphen.
2. In order to avoid hyphens/kebab-case, I started to name colors with numbers. This scenario still faces the problem exposed on this thread.

Colors name: accent1, ff0000redcolor
HTML: <h1 class="has-accent-1-color has-text-color">Text</h1> <h1 class="has-ff-0000-redcolor-color has-text-color">Text</h1>
CSS: .has-accent1-color { color:#000000; } .has-ff0000redcolor-background-color { background-color:#ff0000; }

**Comment by marceloaof** [comment]
I am going to expand the latest comment. I just want to let you know that remains a problem regarding your implementation of global colors. Global colors containing Capitalized-Letters used to be a problem and was solved. But global colors containing numb3rs are still not rendered on frontend.

In Gutenberg 10.8.1 -> (Site) editor -> (Global) styles sidebar -> (Color) palette -> I create 2 colors:
1. accent1
2. ff0000redcolor
The names are saved like that. Slugs are automatically generated as
1. --accent-1
2. --ff-0000-redcolor
I create a new post -> I apply those colors to paragraph blocks -> the colors are rendered correctly both on the front-end and on the editor. OK. ✅

In GeneratePress 3.1.1 -> Customizer -> Colors sidebar -> Global colors -> I create 2 colors:
1. accent1
2. ff0000redcolor
The names are saved like that. Slugs are automatically generated as
1. --accent1
2. --ff0000redcolor
I create a new post -> I apply those custom colors to paragraph blocks -> the colors are rendered correctly on the editor: element{ color:var(--accent1); } ), but on the front-end the colors are not rendered. BUG. ❌

Reason: although global colors are exposed correctly in frontend as :root { --**accent1** and --**ff0000redcolor**}, on each paragraph block the global color is printed incorrectly.
Examples: < h1 class="has-**accent-1**-color has-text-color">This text is not colored!< /h1>
And the other one: < h1 class="**has-**ff-0000-redcolor**-color has-text-color">This text is also not colored!< /h1>
